MindsMeshHeroku/config/routes.rb
# MindsMesh (c) 2013

Mindsmesh::Application.routes.draw do

  resources :removes


  resources :background_jobs

  resources :email_campaigns
  resources :post_hashtags
  resources :hashtags
  resources :feedback_bugs

  resources :entity_user_lms

  resources :entity_lms
  resources :lms_providers

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks"}

  #rails generate versionist:new_controller notifications api/V1
  #then adapt the generated files
    
  namespace 'api' do
    api_version(:module => "V1", :path=> {:value => "v1"}) do
      resources :posts, only: [:index, :show, :create] do
        member do
          get 'with_children'
          get 'with_family'
          get 'likes'
          get 'likes/with_parents', action: 'likes_with_parents'
          post 'like'
          post 'unlike'
          post 'replies', action: 'create_reply'
        end
        collection do
          get 'with_family', action: 'posts_with_family'
        end
      end
      resources :notifications, only: [:show] do
            collection do
                get 'grouped/with_parents', action: 'grouped_with_parents'
            end
            member do
                post 'mark_as_read'
            end
      end
      resources :replies, only: [:show] do
        member do
          get 'likes'
          get 'likes/with_parents', action: 'likes_with_parents'
          post 'like'
          post 'unlike'
        end
      end
      resources :topics, only: [:show, :create] do
        member do
          get 'posts'
          get 'posts/with_family', action: 'posts_with_family'
          post 'join'
          post 'leave'
        end
      end
      resources :groups, only: [:show, :create] do
        member do
            get 'posts'
            get 'posts/with_family', action: 'posts_with_family'
            post 'join'
            post 'leave'
        end
      end
      resources :users, only: [:show] do
        member do
          get 'with_children'
          post 'create'
        end
        #collection do
        #  get :batch
        #end
      end
      post '/session/login'
      get '/session/me'
      get '/home/posts'
      get '/home/posts/with_parents' => 'home#posts_with_parents'
      get '/home/entities'
      get '/home/entities/with_children' => 'home#entities_with_children'
      get '/home/topics'
      post '/home/search_topics'
      post '/posts/encode_video' => 'posts#encode_video'
      post '/home/register_device'
      post "/home/entities" => "home#create_entity_request"
      match '*path' => 'base#render_404'
    end  
  end

  resources :notifies, only: [:index, :destroy]

  #for now, we're sending IRs to login, but we plan on making a custom login page showing invitor, entity and topic
  resources :invite_requests, only: [:create] #, :show
  #get "invited/:id" => "invite_requests#show", as: :nice_invite_request
  get "invited/:id(/:name)" => "home#denied", as: :nice_invite_request

  mount MailsViewer::Engine => '/delivered_mails'
  
  get "/privacy" => "pages#privacy"
  get "/product_tour" => "pages#product_tour"
  get "/terms"   => "pages#terms"
  get "/support" => "pages#privacy"
  get "/faq"     => "pages#privacy"
  get "/saml"     => "home#saml"
  get "/about"   => "pages#privacy"

  resources :notifications, only: [:show]
    resources :entity_advanced_settings
          resources :hashtags
  #general resources, most of these have permissions
  resources :questionnaires, only: [:index, :show, :destroy]
  resources :entities do
      get :settings
      get :lti
      post :lti
    collection do
      get 'select2_filter', format: 'js'
      get 'datatable_filter', format: 'json'
    end
  end
  
  resources :entity_users
  resources :group_users
  resources :topic_users
    resources :messages
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :more_posts
        put :follow
        put :unfollow
      end
      collection do
          get :filter
          get 'datatable_filter', format: 'json'
          post :import
      end
    end
  resources :topics do
    member do
      put :join
      put :leave
      get :more_posts
    end
    collection do
      get :filter
      get 'datatable_filter', format: 'json'
      post :import
    end
  end
    
  resources :rosters do
      member do
      end
      collection do
          get :filter
          get 'datatable_filter', format: 'json'
          post :import
      end
  end

    
  resources :groups do
    member do
        put :join
        put :leave
        get :more_posts
    end
  end

  resources :posts, except: [:new, :create, :edit] do
    member do
      post 'replies', action: 'create_reply'
      post 'like'
      post 'unlike'
    end
  end
  resources :post_attachments, only: [:destroy]
  resources :replies, only: [:update, :destroy] do
    member do
      put 'like'
    end
  end
  
  #creating an account
  get "home/login" => "home#ucmesh_login", :constraints => { :domain => "ucmesh.com" }
  get "home/login" => "home#edumesh_login", :constraints => { :domain => "edumesh.com" }
  get "home/login"
  get "session/logout"
  get "settings" => "settings#index"
  put "session/switch"
  match "/auth/:provider/callback" => "session#create"
  match "/auth/failure" => "home#denied"
    
  match "/auth/failure" => "home#denied"

  #relating to an entity
  get "home/entities"
  post "home/entities" => "home#create_entity_request", as: 'home_create_entity_request'
  get "home/confirm/:confirmation_token" => "home#confirm_entity_request", as: 'home_confirm_entity_request'
    
  post "home/signup" => "home#create_signup_request", as: 'home_create_signup_request'
  get "home/confirm_signup/:confirmation_token" => "home#confirm_signup_request", as: 'home_confirm_signup_request'

  get "join/:token" => "home#join_entity"

  #client, a user associated to entity
  match "fb_canvas" => 'home#fb_canvas'
  match "home/search" => 'home#search_users'
  match 'switch_user' => 'switch_user#set_current_user'
  get '/' => 'home#index', as: 'home_index'
  get "home/more_posts"
  get "hashtags/more_posts"
  get "hash/:tag" => "hashtags#show"
  post "home/create_post"
  post "home/create_message"
  post "home/change_access_token"
  get '/home/topics'
  post 'home/fb_requests_sent'
  
  #ajax
  get "home/ajax_application", format: 'js'

  #questionnaire
  post "home/feedback"

  #other roles
  #get "home/moderator"
  #get "home/manager"
  #get "home/admin"
  #get "home/master"

  root to: "home#index"
  get "home/denied", as: 'denied'
   
  # Admin section  
  get '/admin' => 'admin#index', as: 'admin_index'
  
  # Admin email manager  3-XII-13
  namespace :admin do

    #get  "select"    => "panels#index",   :as => 'panela_index'
    resources :panels do
      collection do
          get  "index"    => "panels#index",   :as => 'pindex'
          get  "statics"  => "panels#statics", :as => 'statics'
          get  "recent"   => "panels#recent",  :as => 'recent'
          get  "posts"    => "panels#posts",   :as => 'posts'
      end
    end

    resources :campaigns do
      collection do
          post  "groups/"      => "campaigns#groups",   :as => 'groups'
          get   "sendcamp/:id" => "campaigns#sendcamp", :as => 'sendcamp'
      end
    end

    resources :newsletters do
      collection do
          get   "select/:id"           => "newsletters#select",       :as => 'ns_select'
          get   "test/:id"             => "newsletters#test",         :as => 'test'
          get   "send/"                => "newsletters#send",         :as => 'send'
          post  "generalstats/"        => "newsletters#generalstats", :as => 'generalstats'
          get   "settings/"            => "newsletters#settings",     :as => 'settings'
          get   "statics/:id"          => "newsletters#statics",      :as => 'statics'
          get   "categories"           => "newsletters#categories",   :as => 'categories'
          post  "groups/"              => "newsletters#groups",       :as => 'groups'
      end
    end
  end
  
end

MindsMeshHeroku/app/models/group.rb
# MindsMesh (c) 2012-2013


class Group < ActiveRecord::Base

    attr_accessible :description, :entity_user_id, :group_users_count, :name, :posts_count, :slug, :user_id, :privacy, :entity_id
    
    belongs_to :entity, counter_cache: true
    belongs_to :user
    has_many :group_users, dependent: :destroy
    has_many :posts,       dependent: :destroy
    has_many :users, through: :group_users
    has_many :invite_requests, dependent: :destroy
    
    validates_presence_of :name
    
    attr_accessor :entity_user, :entity_user_id
    before_validation :set_entity_user_correctly, on: :create
    
    def entity_user_join(entity_user1,admin=false)
        raise 'nil argument' if entity_user1.nil?
        gu = group_users.where(user_id: entity_user1.user.id).first_or_initialize
        if admin
            gu.role_i = 1
        end
        gu.save
        
    end
    
    def entity_user_leave(entity_user1)
        raise 'nil argument' if entity_user1.nil?
        group_users.where(user_id: entity_user1.user.id).first_or_initialize.destroy
    end
    
    def set_entity_user_correctly
        if entity_user_id
            self.entity_user=EntityUser.find(entity_user_id)
        end
        if entity_user
            self.entity  = entity_user.entity
            self.user    = entity_user.user
        end
    end

end

MindsMeshHeroku/app/controllers/admin/campaigns_controller.rb
# MindsMesh, Inc. (c) 2012-2013

class Admin::CampaignsController < ApplicationController

  #load_and_authorize_resource

  respond_to :html, :json, :js
  
  # TODO: name these comments properly with all the matching URLs to each action
  # GET /admin/campaigns
  def index
    @admin_campaigns = Admin::Campaign.paginate(:page => params[:page], :per_page => 25).order('id DESC')
  end

  # GET /admin/campaigns/1
  def show
     @admin_campaign = Admin::Campaign.find(params[:id])
  end

  # GET /admin/campaigns/new
  def new
    @admin_campaign = Admin::Campaign.new
  end

  def groups

    #return render :text => params[:admin_campaign].inspect
     
    if params[:admin_campaign][:kind] == 'everybody' 
        @data = Admin::Campaign.create_campaign(params[:admin_campaign])
        # return render :text => @data
        return redirect_to admin_campaigns_path , notice: 'Campaign was created.'
    end
    
    @scheduled      = params[:admin_campaign][:scheduled]
    @futuretime     = params[:admin_campaign][:futuretime]
    @newsletter_id  = params[:admin_campaign][:newsletter_id]
    @kind           = params[:admin_campaign][:kind]
    @admin_campaign = Admin::Campaign.new
    @data           = Admin::Newsletter.get_group(params[:admin_campaign][:entity_id], params[:admin_campaign][:kind])  # pass the array

    # return render :text => @data

  end

  # POST /admin/campaigns
  def create
    #return render :text => params[:admin_campaign]
    @data = Admin::Campaign.create_campaign(params[:admin_campaign])
    redirect_to admin_campaigns_path , notice: 'Campaign was created.'
  end

 # POST /admin/campaigns/send
  def sendcamp
    data = Admin::Campaign.send_mails_and_save(params[:id])
    redirect_to admin_campaigns_path, notice: 'Campaign was delivered.'
  end

  # GET /admin/campaigns/1/edit
  def edit
    @admin_campaign = Admin::Campaign.find(params[:id]) 
  end

  # PUT /admin/campaigns/1
  def update
    @admin_campaign = Admin::Campaign.find(params[:id])

    if @admin_campaign.update_attributes(params[:admin_campaign])
      redirect_to admin_campaigns_path, notice: 'Campaign was updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /admin/campaigns/1
  def destroy
    @admin_campaign = Admin::Campaign.find(params[:id])
    @admin_campaign.destroy
    redirect_to admin_campaigns_url
  end
end

MindsMeshHeroku/app/views/admin/campaigns/_form.html.erb
<%= simple_form_for(@admin_campaign) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs" style="width:30%;">
    <%= f.input :futuretime, :class => "datepicker", :label => "Scheduled Date" %>
  </div>

  <!-- starts -->
  <label>Send:</label>
  <div style="padding:8px;margin:4px;border:1px dotted gray;width:75%;"> 
      <select name="admin_campaign[scheduled]" id="selecttime">
          <option value="1" selected="selected">Immediately</option>
          <option value="3">Send 24hrs after registration</option>
          <option value="2">Schedule</option>
      </select>

    <div class="form-actions">
       <%= f.button :submit %>
    </div>
 <!-- ends -->
<% end %>

MindsMeshHeroku/app/views/admin/campaigns/create.html.erb
<div class="headline3">Campaign created</div>


<div style="padding:15px;margin:19px;background-color:#fff;">
<%# = @data.inspect %>
    <%= @data[:usersfound] %> users found. <%= @data[:emails] %> email has been sent. 
    <% if @data[:scheduled] == 1 %>
        <%= link_to 'Please view historic for details.', "/admin/newsletters/statics/#{@data[:nl_id]}" %><br /><br />
    <% else%>    
         Campaign <%= @data[:schedule] %> scheduled.
    <% end %>

    <p><%= link_to image_tag('icon-back.png', :title=>'Go back', :alt=>'Go back'), admin_newsletters_path %></p>

</div>

MindsMeshHeroku/app/views/admin/campaigns/edit.html.erb
<div id="admincontainer">
    <div class="headline3">Editing Campaign</div>

    <h2><%= @admin_campaign.newsletter.title %></h2>
    <div style="margin:10px;padding:7px;">
       <%= render 'form' %>
    </div>

    <br />
    <div style="text-align:left;">
          <%= link_to image_tag('icon-back.png', :title=>'Go back', :alt=>'Go back'), admin_campaigns_path %>
          <%= link_to image_tag('icon-back.png', :title=>'Go back', :alt=>'Go back'), admin_newsletters_path %>
    </div>
</div>

MindsMeshHeroku/app/views/admin/campaigns/groups.html.erb
<div class="headline3">Final step</div>

<div style="padding:10px;margin:6px;background-color:#fff;border: 2px solid gray;">

<h2>Select the <%= @kind %> you want to send this email to:</h2>

<%= simple_form_for(@admin_campaign,  :url => url_for(:controller => 'campaigns', :action => 'create'), :html => { :method => :post, :onsubmit => 'return checkCB();' })  do |f| %>

  <%= f.error_notification %>
  
  <% one_value = false %>

  <input type="hidden" name="admin_campaign[kind]" value="<%= @kind %>">
  <input type="hidden" name="admin_campaign[newsletter_id]"  value="<%= @newsletter_id %>">
  <input type="hidden" name="admin_campaign[futuretime]" value="<%= @futuretime %>">
  <input type="hidden" name="admin_campaign[scheduled]"  value="<%= @scheduled %>">


  <div class="form-inputs">

  <% @data.each do | d | %>
  <!-- %= d.inspect % -->
      <%=  content_tag :h3, "College: #{d[:name]} "  %>

      <% if @kind == 'users' %>    
          <% if d.has_key?(:users) %>
              <% one_value = true %>
              <% d[:users].each do |k,v| %>
              <div style="margin:3px;padding:3px;border:1px dotted #e0e0e0;">
                  <input type="checkbox" class="eleclass" name="admin_campaign[entity_ids][<%= d[:id] %>][user_ids][<%= v  %>]" value="<%= v  %>"> <%= k  %>
              </div>
              <% end %>
          <% else %>
             <p>No groups in this college yet.</p>
          <% end %>  
      <% end %>

      <% if @kind == 'groups' %>    
          <% if d.has_key?(:groups) %>
              <% one_value = true %>
              <% d[:groups].each do |g| %>
              <div style="margin:3px;padding:3px;border:1px dotted #e0e0e0;">
                <input type="checkbox" class="eleclass" name="admin_campaign[entity_ids][<%= d[:id] %>][user_ids][<%= g.id  %>]" value="<%= g.id  %>"> <%= g.name  %> 
                </div>
              <% end %>
          <% else %>
             <p>No groups in this college yet.</p>
          <% end %>  
      <% end %>

      <% if @kind == 'topics' %> 
          <% if d.has_key?(:topics) %>
          <% one_value = true %>
           <input type="hidden" name="admin_campaign[entity_id]"  value="<%= d[:id] %>">
              <% d[:topics].each do |t| %>
              <div style="margin:3px;padding:3px;border:1px dotted #e0e0e0;">
                  <input type="checkbox" class="eleclass" name="admin_campaign[entity_ids][<%= d[:id] %>][user_ids][<%= t.id  %>]" value="<%= t.id  %>"> <%= t.name  %> 
              </div>
              <% end %>
          <% else %>
             <p>No topics in this college yet.</p>
          <% end %>  
      <% end %>

  <% end %>  
  <br />

  </div> <!-- form inputs -->
  
  <div class="form-actions">
      <%  if one_value == true  %>
         <input class="btn" name="commit" type="submit" value="Create Campaign">
      <% end %> 
  </div>

  </form>
<% end %>

</div>

<script type="text/javascript">

$(document).ready(function () {
    $('#selectall').click(function () {
        $('.selectedId').prop('checked', isChecked('selectall'));
    });
});
    
function isChecked(checkboxId) {
    var id = '#' + checkboxId;
    return $(id).is(":checked");
}

function resetSelectAll() {
    // if all checkboxes are selected, check the selectall CB
    // and of course viceversa
    if ($(".selectedId").length == $(".selectedId:checked").length) {
        $("#selectall").attr("checked", "checked");
    } else {
        $("#selectall").removeAttr("checked");
    }

    if ($(".selectedId:checked").length > 0) {
        $('#edit').attr("disabled", false);
    } else {
        $('#edit').attr("disabled", true);
    }
}

function checkCB() {
         
         if ( $(".eleclass:checked").length < 1)
         {
            alert('Choose at least one element');
            return false;
         }
        // return confirm("Are you sure you want to send this email?");
}

</script>

MindsMeshHeroku/app/views/admin/campaigns/index.html.erb
<div id="admincontainer">

<div class="headline3">Campaigns</div>
<br />
<table style="border:1px solid gray;margin:18px auto;text-align:left;padding:6px;background-color:#fff;">
  <tr style="background-color:#d9d9d9;color:#fff;font-weight:bold;font-size:13pt;">
    <th>Newsletter</th>
    <th>To</th>
    <th>Scheduled</th>
    <th>Date to deliver</th>
    <th>Created</th>
    <th>Emails</th>
    <th>Send</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%  sch_options   = {1=>'Immediately', 2=>'Scheduled', 3 => '24 h aft. reg.', 4 => 'Week aft. reg.'} %>
<% @admin_campaigns.each do |admin_campaign| %>
   <tr style="border:1px dotted gray;margin:18px auto;padding:3px;">
    <td><%= admin_campaign.newsletter.title %></td>
    <td><%= admin_campaign.kind %></td>
    <td><%= sch_options[admin_campaign.scheduled] %></td>
    <% if admin_campaign.scheduled == 2 %> 
        <td><%= admin_campaign.futuretime %>
            <%#=localize(admin_campaign.futuretime, :format => :long) %>
        </td>
    <% else %>
        <td>Not scheduled</td>
    <% end %>
    <td><%= admin_campaign.created_at %></td>
    <td><%= admin_campaign.campaigns_users.size  %></td>
    <td><%= link_to raw('<i class="icon-envelope icon-white"></i>'), sendcamp_admin_campaigns_path(admin_campaign), :alt=>'Send now', :title=>'Send now',:confirm => "Are you sure to deliver this campaign now?" %>
    <td><%= link_to raw('<i class="icon-tablet icon-white"></i>'), edit_admin_campaign_path(admin_campaign), :alt=>'Edit Campaign', :title=>'Edit Campaign' %></td>
    <td><%= link_to raw('<i class="icon-trash icon-white"></i>'), admin_campaign, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<div style="text-align:center;margin:5px;">
<%= will_paginate @admin_campaigns %>
</div>

<br />
    <div style="text-align:left;">
          <%= link_to image_tag('icon-back.png', :title=>'Go back', :alt=>'Go back'), admin_newsletters_path %>
    </div>
</div>    

MindsMeshHeroku/app/views/admin/campaigns/new.html.erb
<h1>New admin_campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_campaigns_path %>

MindsMeshHeroku/app/views/admin/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kind:</b>
  <%= @admin_campaign.kind %>
</p>

<p>
  <b>Value:</b>
  <%= @admin_campaign.value %>
</p>

<p>
  <b>Element id:</b>
  <%= @admin_campaign.element_id %>
</p>

<p>
  <b>Historic:</b>
  <%= @admin_campaign.historic %>
</p>

<p>
  <b>Newsletter:</b>
  <%= @admin_campaign.newsletter.title %>
</p>


<%= link_to 'Edit', edit_admin_campaign_path(@admin_campaign) %> |
<%= link_to 'Back', admin_campaigns_path %>