MindsMeshHeroku/config/routes.rb
# MindsMesh (c) 2013

Mindsmesh::Application.routes.draw do

  resources :removes


  resources :background_jobs

  resources :email_campaigns
  resources :post_hashtags
  resources :hashtags
  resources :feedback_bugs

  resources :entity_user_lms

  resources :entity_lms
  resources :lms_providers

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks"}

  #rails generate versionist:new_controller notifications api/V1
  #then adapt the generated files
    
  namespace 'api' do
    api_version(:module => "V1", :path=> {:value => "v1"}) do
      resources :posts, only: [:index, :show, :create] do
        member do
          get 'with_children'
          get 'with_family'
          get 'likes'
          get 'likes/with_parents', action: 'likes_with_parents'
          post 'like'
          post 'unlike'
          post 'replies', action: 'create_reply'
        end
        collection do
          get 'with_family', action: 'posts_with_family'
        end
      end
      resources :notifications, only: [:show] do
            collection do
                get 'grouped/with_parents', action: 'grouped_with_parents'
            end
            member do
                post 'mark_as_read'
            end
      end
      resources :replies, only: [:show] do
        member do
          get 'likes'
          get 'likes/with_parents', action: 'likes_with_parents'
          post 'like'
          post 'unlike'
        end
      end
      resources :topics, only: [:show, :create] do
        member do
          get 'posts'
          get 'posts/with_family', action: 'posts_with_family'
          post 'join'
          post 'leave'
        end
      end
      resources :groups, only: [:show, :create] do
        member do
            get 'posts'
            get 'posts/with_family', action: 'posts_with_family'
            post 'join'
            post 'leave'
        end
      end
      resources :users, only: [:show] do
        member do
          get 'with_children'
          post 'create'
        end
        #collection do
        #  get :batch
        #end
      end
      post '/session/login'
      get '/session/me'
      get '/home/posts'
      get '/home/posts/with_parents' => 'home#posts_with_parents'
      get '/home/entities'
      get '/home/entities/with_children' => 'home#entities_with_children'
      get '/home/topics'
      post '/home/search_topics'
      post '/posts/encode_video' => 'posts#encode_video'
      post '/home/register_device'
      post "/home/entities" => "home#create_entity_request"
      match '*path' => 'base#render_404'
    end  
  end

  resources :notifies, only: [:index, :destroy]

  #for now, we're sending IRs to login, but we plan on making a custom login page showing invitor, entity and topic
  resources :invite_requests, only: [:create] #, :show
  #get "invited/:id" => "invite_requests#show", as: :nice_invite_request
  get "invited/:id(/:name)" => "home#denied", as: :nice_invite_request

  mount MailsViewer::Engine => '/delivered_mails'
  
  get "/privacy" => "pages#privacy"
  get "/product_tour" => "pages#product_tour"
  get "/terms"   => "pages#terms"
  get "/support" => "pages#privacy"
  get "/faq"     => "pages#privacy"
  get "/saml"     => "home#saml"
  get "/about"   => "pages#privacy"

  resources :notifications, only: [:show]
    resources :entity_advanced_settings
          resources :hashtags
  #general resources, most of these have permissions
  resources :questionnaires, only: [:index, :show, :destroy]
  resources :entities do
      get :settings
      get :lti
      post :lti
    collection do
      get 'select2_filter', format: 'js'
      get 'datatable_filter', format: 'json'
    end
  end
  
  resources :entity_users
  resources :group_users
  resources :topic_users
    resources :messages
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :more_posts
        put :follow
        put :unfollow
      end
      collection do
          get :filter
          get 'datatable_filter', format: 'json'
          post :import
      end
    end
  resources :topics do
    member do
      put :join
      put :leave
      get :more_posts
    end
    collection do
      get :filter
      get 'datatable_filter', format: 'json'
      post :import
    end
  end
    
  resources :rosters do
      member do
      end
      collection do
          get :filter
          get 'datatable_filter', format: 'json'
          post :import
      end
  end

    
  resources :groups do
    member do
        put :join
        put :leave
        get :more_posts
    end
  end

  resources :posts, except: [:new, :create, :edit] do
    member do
      post 'replies', action: 'create_reply'
      post 'like'
      post 'unlike'
    end
  end
  resources :post_attachments, only: [:destroy]
  resources :replies, only: [:update, :destroy] do
    member do
      put 'like'
    end
  end
  
  #creating an account
  get "home/login" => "home#ucmesh_login", :constraints => { :domain => "ucmesh.com" }
  get "home/login" => "home#edumesh_login", :constraints => { :domain => "edumesh.com" }
  get "home/login"
  get "session/logout"
  get "settings" => "settings#index"
  put "session/switch"
  match "/auth/:provider/callback" => "session#create"
  match "/auth/failure" => "home#denied"
    
  match "/auth/failure" => "home#denied"

  #relating to an entity
  get "home/entities"
  post "home/entities" => "home#create_entity_request", as: 'home_create_entity_request'
  get "home/confirm/:confirmation_token" => "home#confirm_entity_request", as: 'home_confirm_entity_request'
    
  post "home/signup" => "home#create_signup_request", as: 'home_create_signup_request'
  get "home/confirm_signup/:confirmation_token" => "home#confirm_signup_request", as: 'home_confirm_signup_request'

  get "join/:token" => "home#join_entity"

  #client, a user associated to entity
  match "fb_canvas" => 'home#fb_canvas'
  match "home/search" => 'home#search_users'
  match 'switch_user' => 'switch_user#set_current_user'
  get '/' => 'home#index', as: 'home_index'
  get "home/more_posts"
  get "hashtags/more_posts"
  get "hash/:tag" => "hashtags#show"
  post "home/create_post"
  post "home/create_message"
  post "home/change_access_token"
  get '/home/topics'
  post 'home/fb_requests_sent'
  
  #ajax
  get "home/ajax_application", format: 'js'

  #questionnaire
  post "home/feedback"

  #other roles
  #get "home/moderator"
  #get "home/manager"
  #get "home/admin"
  #get "home/master"

  root to: "home#index"
  get "home/denied", as: 'denied'
   
  # Admin section  
  get '/admin' => 'admin#index', as: 'admin_index'
  
  # Admin email manager  3-XII-13
  namespace :admin do

    #get  "select"    => "panels#index",   :as => 'panela_index'
    resources :panels do
      collection do
          get  "index"    => "panels#index",   :as => 'pindex'
          get  "statics"  => "panels#statics", :as => 'statics'
          get  "recent"   => "panels#recent",  :as => 'recent'
          get  "posts"    => "panels#posts",   :as => 'posts'
      end
    end

    resources :campaigns do
      collection do
          post  "groups/"      => "campaigns#groups",   :as => 'groups'
          get   "sendcamp/:id" => "campaigns#sendcamp", :as => 'sendcamp'
      end
    end

    resources :newsletters do
      collection do
          get   "select/:id"           => "newsletters#select",       :as => 'ns_select'
          get   "test/:id"             => "newsletters#test",         :as => 'test'
          get   "send/"                => "newsletters#send",         :as => 'send'
          post  "generalstats/"        => "newsletters#generalstats", :as => 'generalstats'
          get   "settings/"            => "newsletters#settings",     :as => 'settings'
          get   "statics/:id"          => "newsletters#statics",      :as => 'statics'
          get   "categories"           => "newsletters#categories",   :as => 'categories'
          post  "groups/"              => "newsletters#groups",       :as => 'groups'
      end
    end
  end
  
end

MindsMeshHeroku/app/controllers/api/v1/home_controller.rb
# MindsMesh (c) 2013

module Api::V1
  class HomeController < BaseController

    def entities
      entities = @current_user.entities
      render json: EntityPresenter.array(entities)
    end

    def entities_with_children
      entities = @current_user.entities
      render json: EntityPresenter.array(entities).map { |ep| ep.with_entity_user_and_topics(@current_user) }
    end

    def topics
      topics = @current_user.topics
      render json: TopicPresenter.array(topics)
    end

    def search_topics
      topics = @current_user.search_topics(params[:q])
      render json: TopicPresenter.array(topics)
    end
    
    #  post "/home/entities" => "home#create_entity_request"
    # link an account to an entity   
    def create_entity_request
      entity = Entity.find_by_email_domain(params[:email])
      eur = @current_user.entity_user_requests.where(entity_id: entity.id, email: params[:email]).first_or_initialize
      eur.generate_and_mail_new_token
      text = eur.save ? "a confirmation email has been sent to #{params[:email]}" : eur.errors.full_messages.to_sentence.to_s
      render json: {message: text}
    end

    #POST /home/register_device
    def register_device
      ud = @current_user.user_devices.where(token: params[:token]).first_or_initialize
      ud.os = params[:os]
      ud.environment = params[:environment]
      ud.name = params[:name]
      ud.model = params[:model]
      if ud.save
        render json: true
      else
        render json: {message: ud.errors.full_messages}
      end
    end

  end
end

MindsMeshHeroku/app/helpers/home_helper.rb
module HomeHelper
    
    
    def resource_name
        :user
    end
    
    def resource
        @resource ||= User.new
    end
    
    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
    
    
    
    
end

MindsMeshHeroku/app/views/home/_feedback.html.erb
<% q = Questionnaire.where(user_id: current_user.id).first_or_initialize.sample_blank_question %>
<% if q %>
<section class="block questionnaire">

<% if q == :q1 %>
  <div class="field">
    <p><%= raw Questionnaire::QUESTIONS[q] %></p>
    <div class="well" style="text-align:center">
      <span class="rating" data-name="<%= q %>">
        <span class="star" data-value="1/5"></span>
        <span class="star" data-value="2/5"></span>
        <span class="star" data-value="3/5"></span>
        <span class="star" data-value="4/5"></span>
        <span class="star" data-value="5/5"></span>
      </span>
    </div>
  </div>
<% elsif [:q2, :q3, :q4, :q5, :q6, :q7].include? q %>
  <div class="field">
    <p><%= raw Questionnaire::QUESTIONS[q] %></p>
    <%= text_area_tag q, '', class: 'input-block-level' %>
  </div>
<% end %>

</section>
<script type="text/javascript">

function questionnaire_answer(field, params) {
  $.post('<%= home_feedback_path %>', params);

  field.html("<h3 style='center'>THANK YOU</h3>");
  $("section.questionnaire").slideUp(1200);
}

$(function() {

  $("section.questionnaire textarea").live('keydown', function(e) {
    //

    if (e.keyCode == 13 && !e.shiftKey && !e.ctrlKey) {
      if ($(this).val().trim().length > 0) {

        var field = $(this).closest('.field');
        var params = {
          name: $(this).attr('name'),
          value: $(this).val()
        };
        questionnaire_answer(field, params);
        return false;

      }
    }

  });

  $("section.questionnaire .rating .star").live('click', function(e) {

    var field = $(this).closest('.field');
    var params = {
      name: $(this).closest('.rating').data('name'),
      value: $(this).data('value')
    };
    questionnaire_answer(field, params);
    return false;


  });

});

</script>
<% end %>

MindsMeshHeroku/app/views/home/ajax_application.js.erb
if ($('#top_menu_left').length) {
  var s = "<%= j render '/partials/application/notifications' %>";
  $('#top_menu_left').append(s);
}

if ($('#top_menu_left').length) {
  var s = "<%= j render '/partials/application/messages' %>";
  $('#top_menu_left').append(s);
}

if ($('#top_menu_right').length) {
  var s = "<%= j render '/partials/application/myaccount' %>";
  $('#top_menu_right').append(s);
 }

var s = "<%= j render '/partials/application/follow_recs' %>";
$('body').append(s);


<% if my_fb_friends_i_should_invite.any? %>

if ($('#sidebar_right').length) {
  var s = "<%= j render '/partials/application/fb_invites_rightbar' %>";
  $('#sidebar_right').append(s);
}


var s = "<%= j render '/partials/application/fb_invites' %>";
$('body').append(s);


 if ($.cookie('suggest_follows') == "true") {
   var _callback = function() {
     $('#follow_recs_modal').modal();
     $.cookie('suggest_follows', 'false');
   }
   setTimeout(_callback, 1000);
 } else if ($.cookie('suggest_invites') == "true") {
   var _callback2 = function() {
     $('#fb_friends_modal').modal();
     $.cookie('suggest_invites', 'false');
   }
   setTimeout(_callback2, 1000);
 }

 <% end %>

MindsMeshHeroku/app/views/home/confirm_signup_request.html.erb
<div id="main_index">
    <div id="features">
    	<div id="featurediv">
    		<div class="container fix-sections">
    			<h2><%= @srr.email %> you are about to join <%= @entity.entity_users_count %> others from <%= @entity.name %> </h2>
    				<div style="width:100%;text-align:center">
    					<% if @eu.nil? %>
   						 <% else %>
     						 <% @eu.each do |fb_friend| %>
        						<%= image_tag fb_friend.user.photo_url, width: 50 %>
        
      						<% end %>
    					<% end %>
     			    </div>
    
    			<h3>Tell us a bit about yourself to finish registration below</h3>

    			<div class="row">
				<div class="span3"></div>
				<div class="span3">
					<div style="width:100%;text-align:center;padding-top:60px">
		     			<%= link_to image_tag('connect-facebook-button.png'), user_omniauth_authorize_path(:edu_facebook, confirmation_token: params[:confirmation_token]), id: 'login_facebook' %>
						<br/>
					</div>
				</div>
 		   		<div class="span1"><h2 style="width:100%;text-align:center;padding-top:70px">or</h2></div>
 		    	<div id="dev_signup" class="span2">
 		    	<% resource.email = @srr.email %>
					<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  					<%= devise_error_messages! %>
  					<%= hidden_field_tag 'conf_token', params[:confirmation_token] %>
					<div><%= f.label :name %>
  						<%= f.text_field :name, :autofocus => true %></div>
  				
  					<div><%= f.label :email %>
  						<%= f.email_field :email %></div>

  					<div><%= f.label :password %>
  						<%= f.password_field :password %></div>

  					<div><%= f.label :password_confirmation %>
  						<%= f.password_field :password_confirmation %></div>

  					<div><%= f.submit "Finish Registration", :id => 'sign-up' %></div>
				<% end %>
           		</div>
 
			</div>
		</div>
	</div>
</div>
</div>

MindsMeshHeroku/app/views/home/entities.haml
#entity-email
  = form_tag home_create_entity_request_path, remote: true do |f|
    = text_field_tag :email, '', placeholder: "joe@uncc.edu"
    = submit_tag '', id: 'submit'

#entity_request_modal.modal.hide.fade
  .modal-header
    %button.close{data: {dismiss: "modal"}}
      ×
    %h3 MindsMesh.com
  .modal-body
    %h2
  .modal-footer
    %a.btn.btn-primary{href: "#", data: {dismiss: "modal"}}
      Yes, I understand

MindsMeshHeroku/app/views/home/index.html.erb
<div id="main_index">
<%# length forces select * instead of counts, for the list is needed in this request %>

<%= render '/posts/new_post_home', topic_user: nil %>
<%= render '/posts/posts', posts: @posts, title: "My Mesh" %>
</div>

<div data-sidebar="left" class="sidebar_content">
  <ul class="nav blue-nav nav-list">
    <a href="#"
      id="myaccount"
      class="dropdown-toggle"
      data-toggle="dropdown">
      <%= link_to image_tag(current_user.photo_url, :width => 50,:style => "margin-top:8px"), current_user %>
      <%= link_to current_user.name, current_user %>
  </a>
   <br/>
   <br/>

    <li class="nav-header">
      my classes
    </li>
    <% current_user.topic_users.each do |topic_user| %>
      <% topic = topic_user.topic %>
        <%= li link_to(icon_text('book', truncate(topic.name, length: 28)), topic, class: 'tooltiped', title: topic.name) %>
    <% end %>
    <li class="nav-header">
      my groups
    </li>
    <% current_user.group_users.each do |group_user| %>
      <% group = group_user.group %>
        <%= li link_to(icon_text('book', truncate(group.name, length: 28)), group, class: 'tooltiped', title: group.name) %>
    <% end %>
    <%= li link_to(icon_text('plus', 'Create new group'), "#new_group_modal", data: {toggle: 'modal'}, class: 'tooltiped', title: 'Create new group') %>
  </ul>
</div>

MindsMeshHeroku/app/views/home/join_entity.html.erb
<div id="main_index">
    <div id="features">
    	<div id="featurediv">
    		<div class="container fix-sections">
    			<h2>You are about to join <%= @entity.entity_users_count %> others from <%= @entity.name %> </h2>
    				<div style="width:100%;text-align:center">
    					<% if @eu.nil? %>
   						 <% else %>
     						 <% @eu.each do |fb_friend| %>
        						<%= image_tag fb_friend.user.photo_url, width: 50 %>
        
      						<% end %>
    					<% end %>
     			    </div>
    
    			<h3>Tell us a bit about yourself to finish registration below</h3>

    			<div class="row">
				<div class="span3"></div>
				<div class="span3">
					<div style="width:100%;text-align:center;padding-top:60px">
		     			<%= link_to image_tag('connect-facebook-button.png'), user_omniauth_authorize_path(:facebook, confirmation_token: params[:confirmation_token]), id: 'login_facebook' %>
						<br/>
					</div>
				</div>
 		   		<div class="span1"><h2 style="width:100%;text-align:center;padding-top:70px">or</h2></div>
 		    	<div id="dev_signup" class="span2">
					<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :remote => true) do |f| %>
  					<%= devise_error_messages! %>
  					<%= hidden_field_tag 'entity_token', params[:token] %>
					<div><%= f.label :name %>
  						<%= f.text_field :name, :autofocus => true %></div>
  				
  					<div><%= f.label :email %>
  						<%= f.email_field :email %></div>

  					<div><%= f.label :password %>
  						<%= f.password_field :password %></div>

  					<div><%= f.label :password_confirmation %>
  						<%= f.password_field :password_confirmation %></div>

  					<div><%= f.submit "Finish Registration", :id => 'sign-up' %></div>
				<% end %>
           		</div>
 
			</div>
		</div>
	</div>
</div>
</div>

MindsMeshHeroku/app/views/home/topics.haml
#zero_topics