MindsMeshHeroku/config/routes.rb
# MindsMesh (c) 2013

Mindsmesh::Application.routes.draw do

  resources :removes


  resources :background_jobs

  resources :email_campaigns
  resources :post_hashtags
  resources :hashtags
  resources :feedback_bugs

  resources :entity_user_lms

  resources :entity_lms
  resources :lms_providers

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks"}

  #rails generate versionist:new_controller notifications api/V1
  #then adapt the generated files
    
  namespace 'api' do
    api_version(:module => "V1", :path=> {:value => "v1"}) do
      resources :posts, only: [:index, :show, :create] do
        member do
          get 'with_children'
          get 'with_family'
          get 'likes'
          get 'likes/with_parents', action: 'likes_with_parents'
          post 'like'
          post 'unlike'
          post 'replies', action: 'create_reply'
        end
        collection do
          get 'with_family', action: 'posts_with_family'
        end
      end
      resources :notifications, only: [:show] do
            collection do
                get 'grouped/with_parents', action: 'grouped_with_parents'
            end
            member do
                post 'mark_as_read'
            end
      end
      resources :replies, only: [:show] do
        member do
          get 'likes'
          get 'likes/with_parents', action: 'likes_with_parents'
          post 'like'
          post 'unlike'
        end
      end
      resources :topics, only: [:show, :create] do
        member do
          get 'posts'
          get 'posts/with_family', action: 'posts_with_family'
          post 'join'
          post 'leave'
        end
      end
      resources :groups, only: [:show, :create] do
        member do
            get 'posts'
            get 'posts/with_family', action: 'posts_with_family'
            post 'join'
            post 'leave'
        end
      end
      resources :users, only: [:show] do
        member do
          get 'with_children'
          post 'create'
        end
        #collection do
        #  get :batch
        #end
      end
      post '/session/login'
      get '/session/me'
      get '/home/posts'
      get '/home/posts/with_parents' => 'home#posts_with_parents'
      get '/home/entities'
      get '/home/entities/with_children' => 'home#entities_with_children'
      get '/home/topics'
      post '/home/search_topics'
      post '/posts/encode_video' => 'posts#encode_video'
      post '/home/register_device'
      post "/home/entities" => "home#create_entity_request"
      match '*path' => 'base#render_404'
    end  
  end

  resources :notifies, only: [:index, :destroy]

  #for now, we're sending IRs to login, but we plan on making a custom login page showing invitor, entity and topic
  resources :invite_requests, only: [:create] #, :show
  #get "invited/:id" => "invite_requests#show", as: :nice_invite_request
  get "invited/:id(/:name)" => "home#denied", as: :nice_invite_request

  mount MailsViewer::Engine => '/delivered_mails'
  
  get "/privacy" => "pages#privacy"
  get "/product_tour" => "pages#product_tour"
  get "/terms"   => "pages#terms"
  get "/support" => "pages#privacy"
  get "/faq"     => "pages#privacy"
  get "/saml"     => "home#saml"
  get "/about"   => "pages#privacy"

  resources :notifications, only: [:show]
    resources :entity_advanced_settings
          resources :hashtags
  #general resources, most of these have permissions
  resources :questionnaires, only: [:index, :show, :destroy]
  resources :entities do
      get :settings
      get :lti
      post :lti
    collection do
      get 'select2_filter', format: 'js'
      get 'datatable_filter', format: 'json'
    end
  end
  
  resources :entity_users
  resources :group_users
  resources :topic_users
    resources :messages
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :more_posts
        put :follow
        put :unfollow
      end
      collection do
          get :filter
          get 'datatable_filter', format: 'json'
          post :import
      end
    end
  resources :topics do
    member do
      put :join
      put :leave
      get :more_posts
    end
    collection do
      get :filter
      get 'datatable_filter', format: 'json'
      post :import
    end
  end
    
  resources :rosters do
      member do
      end
      collection do
          get :filter
          get 'datatable_filter', format: 'json'
          post :import
      end
  end

    
  resources :groups do
    member do
        put :join
        put :leave
        get :more_posts
    end
  end

  resources :posts, except: [:new, :create, :edit] do
    member do
      post 'replies', action: 'create_reply'
      post 'like'
      post 'unlike'
    end
  end
  resources :post_attachments, only: [:destroy]
  resources :replies, only: [:update, :destroy] do
    member do
      put 'like'
    end
  end
  
  #creating an account
  get "home/login" => "home#ucmesh_login", :constraints => { :domain => "ucmesh.com" }
  get "home/login" => "home#edumesh_login", :constraints => { :domain => "edumesh.com" }
  get "home/login"
  get "session/logout"
  get "settings" => "settings#index"
  put "session/switch"
  match "/auth/:provider/callback" => "session#create"
  match "/auth/failure" => "home#denied"
    
  match "/auth/failure" => "home#denied"

  #relating to an entity
  get "home/entities"
  post "home/entities" => "home#create_entity_request", as: 'home_create_entity_request'
  get "home/confirm/:confirmation_token" => "home#confirm_entity_request", as: 'home_confirm_entity_request'
    
  post "home/signup" => "home#create_signup_request", as: 'home_create_signup_request'
  get "home/confirm_signup/:confirmation_token" => "home#confirm_signup_request", as: 'home_confirm_signup_request'

  get "join/:token" => "home#join_entity"

  #client, a user associated to entity
  match "fb_canvas" => 'home#fb_canvas'
  match "home/search" => 'home#search_users'
  match 'switch_user' => 'switch_user#set_current_user'
  get '/' => 'home#index', as: 'home_index'
  get "home/more_posts"
  get "hashtags/more_posts"
  get "hash/:tag" => "hashtags#show"
  post "home/create_post"
  post "home/create_message"
  post "home/change_access_token"
  get '/home/topics'
  post 'home/fb_requests_sent'
  
  #ajax
  get "home/ajax_application", format: 'js'

  #questionnaire
  post "home/feedback"

  #other roles
  #get "home/moderator"
  #get "home/manager"
  #get "home/admin"
  #get "home/master"

  root to: "home#index"
  get "home/denied", as: 'denied'
   
  # Admin section  
  get '/admin' => 'admin#index', as: 'admin_index'
  
  # Admin email manager  3-XII-13
  namespace :admin do

    #get  "select"    => "panels#index",   :as => 'panela_index'
    resources :panels do
      collection do
          get  "index"    => "panels#index",   :as => 'pindex'
          get  "statics"  => "panels#statics", :as => 'statics'
          get  "recent"   => "panels#recent",  :as => 'recent'
          get  "posts"    => "panels#posts",   :as => 'posts'
      end
    end

    resources :campaigns do
      collection do
          post  "groups/"      => "campaigns#groups",   :as => 'groups'
          get   "sendcamp/:id" => "campaigns#sendcamp", :as => 'sendcamp'
      end
    end

    resources :newsletters do
      collection do
          get   "select/:id"           => "newsletters#select",       :as => 'ns_select'
          get   "test/:id"             => "newsletters#test",         :as => 'test'
          get   "send/"                => "newsletters#send",         :as => 'send'
          post  "generalstats/"        => "newsletters#generalstats", :as => 'generalstats'
          get   "settings/"            => "newsletters#settings",     :as => 'settings'
          get   "statics/:id"          => "newsletters#statics",      :as => 'statics'
          get   "categories"           => "newsletters#categories",   :as => 'categories'
          post  "groups/"              => "newsletters#groups",       :as => 'groups'
      end
    end
  end
  
end

MindsMeshHeroku/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html
  xmlns:fb="https://www.facebook.com/2008/fbml">
<head>
  <title>MindsMesh.com - Collaborate with your classmates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/favicon.ico' %>

  <script type="text/javascript" charset="utf-8">    
    window.APP = {
      current_user: {
        is_signed_in: <%= user_signed_in? %>,
        <% if current_user %>
        id: "<%= current_user.id %>"
        <% end %>
      }
    }
  </script>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="header_small">
<script src="http://js.pusher.com/2.1/pusher.min.js"></script>
	  <script type="text/javascript">
        jQuery(function($){
                $('a[data-target="flare"]').peFlareLightbox();
        });
        //var pusher = new Pusher('52f50cfc590a66fd2fed');
</script>
  <script type="text/javascript">jwplayer.key="6q2XmZIAL0vmbFzfr2kXjH4TVQn0PfvFkmtqwQ==";</script>
  <div id="fb-root"></div>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">

        <% if current_user %>
          <ul class="nav pull-left" id="top_menu_left">
            <li><a id="logo" href="/"><%= image_tag('appicon-72.png', :height => 50, :width => 50) %></a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
          <div style="float:none;margin-left:28%;margin-right:auto" >
          <ul class="nav" id="top_menu_middle">
            <li><input type="text"  placeholder="Search for people or groups" id="searchAll" style="width:380px;margin-top:11px;margin-bottom:4px;"/></li>
          </ul>
          
          </div>
          <ul class="nav pull-right" id="top_menu_right">

            <li><a href="/"><i class="icon-home"></i> Home</a></li>
            <% if current_user.role_i = 30  %>
                <li><a href="/admin"><i class="icon-list"></i> Admin </a></li>
            <% end %>
            <!-- placeholder ajax_application.js -->
          </ul>
        <% end %>

      </div>
    </div>
  </div>

  <div class="container">
    <%= "<div class='alert alert-success'><a class='close' data-dismiss='alert' href='#'>×</a><b>#{notice}</b></div>".html_safe if notice %>
    <%= "<div class='alert alert-error'><a class='close' data-dismiss='alert' href='#'>×</a><b>#{alert}</b></div>".html_safe   if alert %>
    
    <div class="messages" id="messages">
      <div class="modal hide fade reply_modal" id="message_modal">

        <% message = Message.new %>
        <%= form_for(message, url: home_create_message_path(message), remote: true) do |f| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      		 <h3>Who should this message go to?  </h3><input type="text"  placeholder="Search for people to add" id="peopleToAdd" style="width:250px;margin-top:4px;margin-bottom:4px"/>
            
          </div>
          <div class="modal-body">
            <div class="question_area" id="question_area_message">
            </div>
            <div class="clear"></div>
            <div class="answer_area">
              <%= image_tag current_user.photo_url, width: 50 %>
              <p><%= f.text_area :text%></p>
              <p><%= f.hidden_field :user_id, :value => @current_user.id%></p>
              <p><input type="hidden" name="message_receiver_ids" id="message_receiver_ids" ></input></p>
            </div>
          </div>
          <div class="modal-footer">
            <%= f.submit "Send this message", class: 'btn btn-success', data: {display_with: "Sending you message..."}, id: "send-mes" %>
          </div>
        <% end %>

      </div>
    </div>

    <table id="tablecontent" cellpadding="0">
      <tr>
        <td id="main">
          <%= yield %>
          <div class="clear">
          </div>
        </td>
        <% if action_includes_sidebar_right? %>
          <td class="sidebar" id="sidebar_right">
            <%#= render '/home/feedback' if (current_user.posts.size+current_user.replies.size) > 2 %>
        <% if @hidetopic != 1 %>
            <%= render '/topics/new_topic' %>
        <% end %>
            <%= yield 'email_invite_on_topics_show'  %>
            <!-- placeholder ajax_application.js -->
          </td>
        <% end %>
      </tr>
    </table>

    <%= render '/footer' %>
    <%= render '/groups/new_group' %>
  </div>

  <!-- placeholder ajax_application.js -->

<script type="text/javascript">
  $.getScript("<%= home_ajax_application_path %>");
</script>
</body>
</html>

MindsMeshHeroku/app/views/layouts/datatables.html.erb
<!DOCTYPE html>
<html
  xmlns:fb="https://www.facebook.com/2008/fbml">
<head>
  <title>MindsMesh.com - Collaborate with your classmates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/favicon.ico' %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="header_small layout_datatables">
  <div id="fb-root"></div>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">

        <% if current_user %>
          <ul class="nav pull-left" id="top_menu_left">
            <li><a id="logo" href="/"><%= image_tag('appicon-72.png', :height => 50, :width => 50) %></a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
          <div style="float:none;margin-left:28%;margin-right:auto" >
          <ul class="nav" id="top_menu_middle">
            <li><input type="text"  placeholder="Search for people or groups" id="searchAll" style="width:380px;margin-top:11px;margin-bottom:4px;"/></li>
          </ul>
          
          </div>
          <ul class="nav pull-right" id="top_menu_right">
            <li><a href="/"><i class="icon-home"></i> Home</a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
        <% end %>

      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row-fluid">
      <%= "<div class='alert alert-success'><a class='close' data-dismiss='alert' href='#'>×</a><b>#{notice}</b></div>".html_safe if notice %>
      <%= "<div class='alert alert-error'><a class='close' data-dismiss='alert' href='#'>×</a><b>#{alert}</b></div>".html_safe   if alert %>
    </div>

    <%= yield %>
  
    <%= render '/footer' %>
    <%= render '/partials/datatables/master_assign_entity_modal' %>
  </div>


</body>
</html>

MindsMeshHeroku/app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MindsMesh.com - Collaborate with your classmates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/favicon.ico' %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body id="guestlogin" class="header_small">
	  <script type="text/javascript">
        jQuery(function($){
                $('a[data-target="flare"]').peFlareLightbox();
        });
</script>

  <div id="fb-root"></div>
    <div class="navbar">
    <div class="navbar-inner">
      <div class="container">


          <ul class="nav pull-left" id="top_menu_left">
            <li><a id="logo" href="/"><%= image_tag('appicon-72.png') %></a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
          <ul class="nav pull-left" id="top_menu_right">
            <li><a href="/">Home</a></li>
            <li><a id="product_tour" href="/product_tour">Product Tour</a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
          <ul class="nav pull-right" id="top_menu_right">
            <li><%= link_to 'Login',
                    "#login_modal",
                    id: 'try-button',
                    data: {toggle: 'modal'} %></li>
            <!-- placeholder ajax_application.js -->
          </ul>

      </div>
    </div>
  </div>
  <%= render '/partials/application/login' %>
  <div id="homepagesplit" class="container">

  	</div>
  	<div class="features">
  	<div id="featurediv">




          <%= yield %>
</div>
        </div>

  <div class="container">
  	<%= render '/footer' %>
  </div>

</body>
</html>

MindsMeshHeroku/app/views/layouts/edumesh_home_guest.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EduMesh.com - Collaborate with your classmates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/favicon.ico' %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body id="guestlogin" class="header_small">
	  <script type="text/javascript">
        jQuery(function($){
                $('a[data-target="flare"]').peFlareLightbox();
        });
</script>

  <div id="fb-root"></div>
    <div class="navbar">
    <div class="navbar-inner">
      <div class="container">


          <ul class="nav pull-left" id="top_menu_left">
            <li><a id="logo" href="/"><%= image_tag('appicon-72.png') %></a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
          <ul class="nav pull-left" id="top_menu_right">
            <li><a href="/">Home</a></li>
            <li><a id="product_tour" href="/product_tour">Product Tour</a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
          <ul class="nav pull-right" id="top_menu_right">
            <li><%= link_to 'Login',
                    "#login_modal",
                    id: 'try-button',
                    data: {toggle: 'modal'} %></li>
            <!-- placeholder ajax_application.js -->
          </ul>

      </div>
    </div>
  </div>
      <div class="signup" id="signup">
        <div class="modal hide fade" id="signup_request_modal">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    		 <h3>EduMesh.com</h3>
          
        </div>
        <div class="modal-body">
			<h2></h2>
        </div>
        
       <div class="modal-footer">
			<button type="button" class="btn-primary" data-dismiss="modal" aria-hidden="true">I understand</button>
        </div>
    
    </div>
    </div>
    <div id="features">
    <div id="featurediv">
    <div class="container fix-sections">
    <%= "<div class='alert alert-success'><a class='close' data-dismiss='alert' href='#'>×</a><b>#{notice}</b></div>".html_safe if notice %>
    <%= "<div class='alert alert-error'><a class='close' data-dismiss='alert' href='#'>×</a><b>#{alert}</b></div>".html_safe   if alert %>
	<%= render '/partials/application/edumesh_login' %>
	<div class="row edumesh_home">
		<div style="width:480px">
			<h2 style="margin-top:20px;text-align:left;">EduMesh is a Intellectual Social Network for Your School</h2>
			<p style="text-align:left">EduMesh allows secure collaboration with classmates and faculty over classes and campus life.</p>
			<div id="new_signup" class="signup-hold">
			<h3 style="color:white;font-size:20px;">Join Your School's Social Network for Free</h3>
			<% @signup_request = SignupRequest.new %>
			<%= form_for(@signup_request, url: home_create_signup_request_path, remote: true) do |f| %>
  				<%= f.email_field :email, :class => "input-email", :placeholder => "Enter your school email address" %>
  				
  				<%= f.submit "Sign up" %>
  				<p style="color:white;font-size:11px">Only students and faculty with verified school emails can join your network</p>
			<% end %>
			</div>
 		</div>
 	</div>
  </div></div>
  </div>
 
 

  <div class="container">
  	<%= render '/footer' %>
  </div>
  
  

</body>
</html>

MindsMeshHeroku/app/views/layouts/home_guest.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MindsMesh.com - Collaborate with your classmates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/favicon.ico' %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body id="guestlogin" class="header_small">
	<script type="text/javascript">jwplayer.key="6q2XmZIAL0vmbFzfr2kXjH4TVQn0PfvFkmtqwQ==";</script>
  <div id="fb-root"></div>
    <div class="navbar">
    <div class="navbar-inner style="filter:none">
      <div class="container">


          <ul class="nav pull-left" id="top_menu_left">
            <li><a id="logo" href="/"><%= image_tag('appicon-72.png') %></a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
          <ul class="nav pull-left" id="top_menu_right">
            <li><a id="features_link" href="/">Features</a></li>
            <li><a id="schools_link" href="/">For Schools</a></li>
            <li><a id="product_tour" href="/product_tour">Product Tour</a></li>
            <li><a href="/">About Us</a></li>
            <li><a href="/">Blog</a></li>
            <!-- placeholder ajax_application.js -->
          </ul>
          <ul class="nav pull-right" id="top_menu_right">
            <li><%= link_to 'Login',
                    "#login_modal",
                    id: 'try-button',
                    data: {toggle: 'modal'} %></li>
            <!-- placeholder ajax_application.js -->
          </ul>

      </div>
    </div>
  </div>
  <div id="homepagesplit" class="container">
    <h2><%= @user %></h2>
    <%= "<div class='alert alert-success'><a class='close' data-dismiss='alert' href='#'>×</a><b>#{notice}</b></div>".html_safe if notice %>
    <%= "<div class='alert alert-error'><a class='close' data-dismiss='alert' href='#'>×</a><b>#{alert}</b></div>".html_safe   if alert %>

	<%= render '/partials/application/login' %>
	
	<div class="row">
		<div class="span8">
<div id='mediaplayer'></div>

			<script type="text/javascript">
 			 jwplayer('mediaplayer').setup({
  			  'flashplayer': '/assets/jwplayer.flash.swf',
   				 'id': 'playerID',
   				  'height': '355',
   				  'width': '600',
   				  'image': 'https://s3.amazonaws.com/mindsmesh.com/assets/MindsMeshMovFrame.jpg',
   			 'file': 'https://s3.amazonaws.com/mindsmesh.com/assets/MindsMesh.mov',
 			 });
		</script>
 		</div>
 		<div class="span4">
 			<h2 style="color: white;">MindsMesh transforms a Learning Management System into a vibrant campus community</h2>
 			<%= link_to_function icon_text('check','Get Started'),
                'scrollSchools()',
                id: 'schools_link',
                style: 'font-size: 40px;margin-top:75px;',
                class: 'btn btn-large btn-success input-block-level'%>
             
 		</div>
 	</div>
  </div>
  <div id="features">
    <div id="featurediv">
  	<div class="container fix-sections">
  		<div  class="row">
 		<div class="span2"></div>
		<div class="span4">
			 	<h2>Build A Campus Community</h2>
			 	<br/>
			 	<p>With MindsMesh a university can build a private online social network with the newest web technologies students are used to using with current social media platforms such as Video, Photo, Groups, Events and more.</p>
			 	<p><a href="/product_tour">Read More</a></p>
 		</div>
 		<div class="span6">
 			<img src="/assets/iStock_000022812361_ExtraSmall.jpg"/>
 		</div>
 	</div>

  	</div>
  </div>
   <div id="featurediv">
  	<div class="container fix-sections">
  		<div  class="row">
		<div class="span6 ">
			<img class='pull-right' src="/assets/iStock-charts.jpg" width="268"/>
 		</div>
 		<div class="span4">
 			<h2>Analytics that matter</h2>
 			<br/>
			<p>The university has in depth views at the usage of the platform, and how students are interacting with it.  Mobile usage, Learning Management System access and social media statistics are all available through our advanced yet easy to use analytics platform.</p>
 		</div>
 		<div class="span2"></div>
 	</div>

  	</div>
  	</div>
  	  <div id="featurediv">
  	<div class="container fix-sections">
  		<div  class="row">
  		<div class="span2"></div>
		<div class="span4">
			  <h2>Native mobile apps</h2>
			  <br/>
			  <p class='pull-right' >Today's students and faculty are mobile first in many cases.  Students want to see their LMS content and be social on campus on the go.  MindsMesh provides iPhone, iPad and Android apps all with full LMS, Multimedia and real-time notifications to give a full experience to the end user.</p>
 			<br/>
 			<div style="width:250px;margin-left: 60px; line-height: 200px;">
 			<%= link_to image_tag('appstore.png'), 'https://itunes.apple.com/us/app/mindsmesh/id595862148?mt=8' %>
 		   </div>
 		</div>
 		<div class="span6">
 			<img src="/assets/MindsMeshiPhone.png"/>
 		</div>
 	</div>

  	</div>
  	
  </div>
  	
  </div>
  </div>
    <div id="for-schools" >
    	<div id="featurediv">
    	<div class="container fix-sections">
    	<h2>MindsMesh is designed for school adoption to be easy!</h2>
    	<br/>
    		<div class="row">
		<div class="span4">
			<%= image_tag('e-learning.png') %>
			<br/>
			<p>MindsMesh integrates with Moodle, Blackboard and Sakai through their standard API.  If a partner hosts your equipment thats just fine.</p>
 		</div>
 		<div class="span4">
			
			<%= image_tag('187360_thumbnail.png', style: "margin-top:45px;margin-bottom:56px") %>
			<br/>
			<p>Faculty and staff don't have to re-work their content on the LMS at all.  It just works.</p>
 		</div>
 		
 		<div class="span4">
 			<%= image_tag('iStock_000017973250_ExtraSmall.jpg', style: "margin-top:30px;margin-bottom:30px") %>
			<br/>
			<p>We are obsessed with the cloud which allows us to power your university and deliver a top-notch, managed and reliable platform. </p>
 		</div>
 			</div>

    	
    	</div>
    	</div>
    	<div id="featurediv">
    		<div class="container fix-sections">
    		<h2>Contact us below to get started!</h2>
    		<br/>
    			<div class="row">
		<div class="span3">
    		    	<%= image_tag('Occupations-Technical-Support-Representative-Female-Light-icon.png', class: 'pull-right') %>
    		    	</div>
    		    	<div class="span3">
    		    		<p style="padding-top:20px">Phone: 980-333-8415</p><p> Email: contact@mindsmesh.com</p>
    		    	</div>
    		    	<div class="span1">
    		    		<h2 style="padding-top:30px">OR </h2>
    		    	</div>
    		    	<div class="span3">
    		    		<h3>Try a basic demo!</h3>
    		    		<%= link_to icon_text('check','Sign up'),
                '#login_modal',
                style: 'font-size: 30px;',
                class: 'btn btn-large btn-success input-block-level',
                data: {toggle: 'modal'}  %>
    		    	</div>
    		    </div>
    	</div>
    	</div>
    </div>

  <div class="container">
  	<%= render '/footer' %>
  </div>
</body>
</html>