MindsMeshHeroku/config/routes.rb
# MindsMesh (c) 2013

Mindsmesh::Application.routes.draw do

  resources :removes


  resources :background_jobs

  resources :email_campaigns
  resources :post_hashtags
  resources :hashtags
  resources :feedback_bugs

  resources :entity_user_lms

  resources :entity_lms
  resources :lms_providers

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks"}

  #rails generate versionist:new_controller notifications api/V1
  #then adapt the generated files
    
  namespace 'api' do
    api_version(:module => "V1", :path=> {:value => "v1"}) do
      resources :posts, only: [:index, :show, :create] do
        member do
          get 'with_children'
          get 'with_family'
          get 'likes'
          get 'likes/with_parents', action: 'likes_with_parents'
          post 'like'
          post 'unlike'
          post 'replies', action: 'create_reply'
        end
        collection do
          get 'with_family', action: 'posts_with_family'
        end
      end
      resources :notifications, only: [:show] do
            collection do
                get 'grouped/with_parents', action: 'grouped_with_parents'
            end
            member do
                post 'mark_as_read'
            end
      end
      resources :replies, only: [:show] do
        member do
          get 'likes'
          get 'likes/with_parents', action: 'likes_with_parents'
          post 'like'
          post 'unlike'
        end
      end
      resources :topics, only: [:show, :create] do
        member do
          get 'posts'
          get 'posts/with_family', action: 'posts_with_family'
          post 'join'
          post 'leave'
        end
      end
      resources :groups, only: [:show, :create] do
        member do
            get 'posts'
            get 'posts/with_family', action: 'posts_with_family'
            post 'join'
            post 'leave'
        end
      end
      resources :users, only: [:show] do
        member do
          get 'with_children'
          post 'create'
        end
        #collection do
        #  get :batch
        #end
      end
      post '/session/login'
      get '/session/me'
      get '/home/posts'
      get '/home/posts/with_parents' => 'home#posts_with_parents'
      get '/home/entities'
      get '/home/entities/with_children' => 'home#entities_with_children'
      get '/home/topics'
      post '/home/search_topics'
      post '/posts/encode_video' => 'posts#encode_video'
      post '/home/register_device'
      post "/home/entities" => "home#create_entity_request"
      match '*path' => 'base#render_404'
    end  
  end

  resources :notifies, only: [:index, :destroy]

  #for now, we're sending IRs to login, but we plan on making a custom login page showing invitor, entity and topic
  resources :invite_requests, only: [:create] #, :show
  #get "invited/:id" => "invite_requests#show", as: :nice_invite_request
  get "invited/:id(/:name)" => "home#denied", as: :nice_invite_request

  mount MailsViewer::Engine => '/delivered_mails'
  
  get "/privacy" => "pages#privacy"
  get "/product_tour" => "pages#product_tour"
  get "/terms"   => "pages#terms"
  get "/support" => "pages#privacy"
  get "/faq"     => "pages#privacy"
  get "/saml"     => "home#saml"
  get "/about"   => "pages#privacy"

  resources :notifications, only: [:show]
    resources :entity_advanced_settings
          resources :hashtags
  #general resources, most of these have permissions
  resources :questionnaires, only: [:index, :show, :destroy]
  resources :entities do
      get :settings
      get :lti
      post :lti
    collection do
      get 'select2_filter', format: 'js'
      get 'datatable_filter', format: 'json'
    end
  end
  
  resources :entity_users
  resources :group_users
  resources :topic_users
    resources :messages
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :more_posts
        put :follow
        put :unfollow
      end
      collection do
          get :filter
          get 'datatable_filter', format: 'json'
          post :import
      end
    end
  resources :topics do
    member do
      put :join
      put :leave
      get :more_posts
    end
    collection do
      get :filter
      get 'datatable_filter', format: 'json'
      post :import
    end
  end
    
  resources :rosters do
      member do
      end
      collection do
          get :filter
          get 'datatable_filter', format: 'json'
          post :import
      end
  end

    
  resources :groups do
    member do
        put :join
        put :leave
        get :more_posts
    end
  end

  resources :posts, except: [:new, :create, :edit] do
    member do
      post 'replies', action: 'create_reply'
      post 'like'
      post 'unlike'
    end
  end
  resources :post_attachments, only: [:destroy]
  resources :replies, only: [:update, :destroy] do
    member do
      put 'like'
    end
  end
  
  #creating an account
  get "home/login" => "home#ucmesh_login", :constraints => { :domain => "ucmesh.com" }
  get "home/login" => "home#edumesh_login", :constraints => { :domain => "edumesh.com" }
  get "home/login"
  get "session/logout"
  get "settings" => "settings#index"
  put "session/switch"
  match "/auth/:provider/callback" => "session#create"
  match "/auth/failure" => "home#denied"
    
  match "/auth/failure" => "home#denied"

  #relating to an entity
  get "home/entities"
  post "home/entities" => "home#create_entity_request", as: 'home_create_entity_request'
  get "home/confirm/:confirmation_token" => "home#confirm_entity_request", as: 'home_confirm_entity_request'
    
  post "home/signup" => "home#create_signup_request", as: 'home_create_signup_request'
  get "home/confirm_signup/:confirmation_token" => "home#confirm_signup_request", as: 'home_confirm_signup_request'

  get "join/:token" => "home#join_entity"

  #client, a user associated to entity
  match "fb_canvas" => 'home#fb_canvas'
  match "home/search" => 'home#search_users'
  match 'switch_user' => 'switch_user#set_current_user'
  get '/' => 'home#index', as: 'home_index'
  get "home/more_posts"
  get "hashtags/more_posts"
  get "hash/:tag" => "hashtags#show"
  post "home/create_post"
  post "home/create_message"
  post "home/change_access_token"
  get '/home/topics'
  post 'home/fb_requests_sent'
  
  #ajax
  get "home/ajax_application", format: 'js'

  #questionnaire
  post "home/feedback"

  #other roles
  #get "home/moderator"
  #get "home/manager"
  #get "home/admin"
  #get "home/master"

  root to: "home#index"
  get "home/denied", as: 'denied'
   
  # Admin section  
  get '/admin' => 'admin#index', as: 'admin_index'
  
  # Admin email manager  3-XII-13
  namespace :admin do

    #get  "select"    => "panels#index",   :as => 'panela_index'
    resources :panels do
      collection do
          get  "index"    => "panels#index",   :as => 'pindex'
          get  "statics"  => "panels#statics", :as => 'statics'
          get  "recent"   => "panels#recent",  :as => 'recent'
          get  "posts"    => "panels#posts",   :as => 'posts'
      end
    end

    resources :campaigns do
      collection do
          post  "groups/"      => "campaigns#groups",   :as => 'groups'
          get   "sendcamp/:id" => "campaigns#sendcamp", :as => 'sendcamp'
      end
    end

    resources :newsletters do
      collection do
          get   "select/:id"           => "newsletters#select",       :as => 'ns_select'
          get   "test/:id"             => "newsletters#test",         :as => 'test'
          get   "send/"                => "newsletters#send",         :as => 'send'
          post  "generalstats/"        => "newsletters#generalstats", :as => 'generalstats'
          get   "settings/"            => "newsletters#settings",     :as => 'settings'
          get   "statics/:id"          => "newsletters#statics",      :as => 'statics'
          get   "categories"           => "newsletters#categories",   :as => 'categories'
          post  "groups/"              => "newsletters#groups",       :as => 'groups'
      end
    end
  end
  
end

MindsMeshHeroku/app/models/report/users.rb
# MindsMesh, Inc. (c) 2012-2013

class Report::Users < ActiveRecord::Base

  def self.users_joined(daterange)
	totalcounts = []
	if daterange.nil? || daterange.empty?
	  currenttime = Time.new
	  time = Date.new(currenttime.year, currenttime.month).to_time
	  monthname = Date::MONTHNAMES[time.month] 
	  @users = User.find(:all, :conditions => ['created_at >= ? AND created_at <= ?', time.at_beginning_of_month, time.at_end_of_month])
	  Date.new(currenttime.year, currenttime.month).at_beginning_of_month.upto(Date.new(currenttime.year, currenttime.month).at_end_of_month) do |date|
      totalcounts << @users.select{|u| u.created_at.to_s =~ /#{date.to_s}/}.size

	  end
	else 
	
	date_a = daterange.split(" - ")
	startdate = Date.strptime date_a[0], "%m/%d/%Y"
	enddate = Date.strptime date_a[1], "%m/%d/%Y"

	
	  @users = User.find(:all, :conditions => ['created_at >= ? AND created_at <= ?', startdate, enddate])
	  startdate.upto(enddate) do |date|
          totalcounts << @users.select{|u| u.created_at.to_s =~ /#{date.to_s}/ }.size
	  end
	end
	
	return totalcounts
  end
  
end

MindsMeshHeroku/app/controllers/api/v1/users_controller.rb
module Api::V1
  class UsersController < BaseController
=begin
  def batch
  	return render json: {error: {message: "this operation requires user_ids param separated between underscores. example: 1_12_312_4", code: 2001}}, status: :not_acceptable if params[:user_ids].blank?
  	users = User.where(id: params[:user_ids].split('_'))
  	render json: V1::UserPresenter.array(users)
  end
=end
    
    skip_before_filter :authenticate, only: :create

    def show
      render json: UserPresenter.new(user)
    end

    def with_children
      render json: UserPresenter.new(user).with_children
    end

    def posts
    	posts = user.posts(params.slice(:limit, :before))
    	render json: PostPresenter.array(posts)
    end

    def posts_with_parents
      posts = user.posts.as_feed(params.slice(:limit, :before))
      render json: PostPresenter.array(posts).map(&:with_parents)
    end
      
    def create
        user2 = User.new(:name => params[:name],
                            :email => params[:email],
                            :password => params[:password]
                            )
        user2.save!
        sign_in user2
        entity = Entity.find_by_email_domain(params[:email])
        return render text: entity if entity.is_a? String
        eur = user2.entity_user_requests.where(entity_id: entity.id, email: params[:email]).first_or_initialize
        eur.generate_and_mail_new_token
        text = eur.save
        return render json: UserPresenter.new(user2).as_me
        
    end


    private

    def user
    	@user ||= User.find(params[:id])
    end
      

  end
end

MindsMeshHeroku/app/controllers/users_controller.rb
# MindsMesh, Inc. (c) 2012-2013

class UsersController < ApplicationController
  respond_to :html#, :json, :xml

  load_and_authorize_resource

  layout 'datatables', only: [:index]

  # GET /users
  def index
    respond_with(@users) do |format|
      format.json { render json: UsersDatatable.new(view_context) }
    end
  end
    
  def new
      render :layout => 'pages'
  end

  # GET /users/1
  def show
      topic_ids = current_user.topic_users.map(&:topic_id)
      group_ids = current_user.group_users.map(&:group_id)
    @posts = Post.where('(user_id in (:user_ids) and (topic_id is null or topic_id in (:topic_ids)) and (group_id is null or group_id in (:group_ids)))', :user_ids => @user.id, :topic_ids => topic_ids,:group_ids => group_ids).as_feed(params.slice(:limit, :before))
    @topic_users = @user.topic_users
    @user_follows = @current_user.user_follows.where(:follow_id => @user.id)
    if @user.entity_user_requests.first.nil?
        @email = current_user.email
    else
        @email = @user.entity_user_requests.first.email
    end
    respond_with(@user)
  end
  
  # GET /users/1/more_posts.js
  def more_posts
    @posts = @user.posts.as_feed(params.slice(:limit, :before))
    render '/posts/more_posts', layout: false
  end

  # GET /users/1/edit
  def edit
    @schools = @user.entity_users
    @topics = @user.topic_users
    @groups = @user.group_users
    respond_with(@user)
  end

  # PUT /users/1
  def update
    #@user.update_attributes(params[:user])
    if @user.update_attributes(params[:user])
       sign_in @user, :bypass => true
      flash[:notice] = "User successfully updated."
    end
    respond_with(@user, location: @user)
  end

  # PUT /users/1/follow
  def follow
    UserFollow.create user_id: @current_user.id.to_i, follow_id: @user.id.to_i
    redirect_to @user
  end

  # PUT /users/1/unfollow
  def unfollow
    uf = UserFollow.where(:user_id => @current_user.id.to_i, :follow_id => @user.id.to_i)
    uf.destroy(uf)
    redirect_to @user
  end
    
  # DELETE /users/1
  def destroy
    @user.destroy
    respond_with(@user)
  end
    
  def import
      User.import(params[:file])
      redirect_to root_url, notice: "Users imported."
  end
end

MindsMeshHeroku/app/helpers/users_helper.rb
module UsersHelper
end

MindsMeshHeroku/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br />
    <%= f.text_field :photo_url %>
  </div>
  
  <h3>Current Schools </h3>
      <% @schools.each do |school| %>
      	<div class="schools-manage" value="<%= school.id %>" class="schools"><%= school.entity.name %><select name="<%= school.id %>" id="school_role_i">
      	<% if school.role_i == 1 %>
  <option value="0">User</option>
  <option value="1" selected>School Administrator</option>
  <% else %>
    <option value="0" selected>User</option>
  <option value="1">School Administrator</option>
  <% end %>
</select><a href='/entity_users/<%= school.id %>' class='btn btn-mini'>x</a></div>
      <% end %>
      
        <h3>Current Topics</h3>
      <% @topics.each do |topic| %>
      	<div class="topics-manage" value="<%= topic.id %>" class="schools"><%= topic.topic.name %><select name="<%= topic.id %>" id="topic_role_i">
      	<% if topic.role_i == 1 %>
  <option value="0">User</option>
  <option value="1" selected>Teacher</option>
  <% else %>
    <option value="0" selected>User</option>
  <option value="1">Teacher</option>
  <% end %>
</select><a href='/topic_users/<%= topic.id %>' class='btn btn-mini'>x</a></div>
      <% end %>
      
        <h3>Current Groups </h3>
      <% @groups.each do |group| %>
      	<div class="groups-manage" value="<%= group.id %>" class="schools"><%= group.group.name %><select name="<%= group.id %>" id="group_role_i">
      	<% if group.role_i == 1 %>
  <option value="0">User</option>
  <option value="1" selected>Group Administrator</option>
  <% else %>
    <option value="0" selected>User</option>
  <option value="1">Group Administrator</option>
  <% end %>
</select><a href='/group_users/<%= group.id %>' class='btn btn-mini'>x</a></div>
      <% end %>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

MindsMeshHeroku/app/views/users/index.html.erb
 <%= render '/admin/admin_menu', posts: @posts %>
<table data-source="<%= users_url(format: :json) %>">
  <thead>
    <tr>
      <th>Name</th>
      <th>Creation</th>
      <th>Entities</th>
      <th>Topics</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<h2>Import Users</h2>

<%= form_tag import_users_path, multipart: true do %>
  
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

MindsMeshHeroku/app/views/users/show.html.erb
<%= render '/posts/posts', posts: @posts %>

<div data-sidebar="left" class="sidebar_content">
  <div style="padding:0 0 20px 20px;">

    <center><%= image_tag @user.photo_url('large') %></center>
    
  </div>
      <% if @user_follows.empty? %>
  <div style="padding: 0 0 0 5px">
    <%= link_to follow_user_path(@user),
                method: 'put',
                id: 'Follow',
                class: 'btn btn-large btn-success input-block-level',
                data: {disable_with: "hold on..."} do
                %>
                <i class="icon-check" style="font-size:36px"></i>
                <br />
                <span style="font-size:20px">Follow this user</span>
                <% end %>
  </div>
  <% end %>
  <ul class="nav blue-nav nav-list">
    <li class="nav-header">
      <%= @user.name %>
    </li>
    <%= li link_to  icon_text('facebook-sign', 'facebook profile'),
                    @user.fb_url,
                    target: '_blank' %>
    <% if @user_follows.present? %>

      <%= li link_to  icon_text('signout', 'unfollow this user'),
                      unfollow_user_path(@user),
                      method: 'put',
                      id: 'leave',
                      data: {disable_with: "hold on..."}
                      %>
    <% end %>
    
    <li class="nav-header">
      friends
    </li>
    <% @user.fb_friends.are_registered.map(&:friend_user).each do |user| %>
      <li>
        <%= link_to user, class: 'tooltiped', title: user.name do %>
          <%= image_tag user.photo_url, width: 30 %>
          <%= user.name %>
        <% end %>
      </li>
    <% end %>

    <% if current_user.master? %>
      <li class="nav-header">master</li>
      <%= li link_to 'Log in as..', "/switch_user?scope_identifier=user_#{@user.id}"%>
      <%= li @user.access_token, style: 'font-size:9px;' %>
      <%= li @email, style: 'font-size:9px;' %>
      <%= li "#{@user.user_devices.count} devices", style: 'font-size:9px;' %>
      <%= li "last seen @ #{localized_short_format(@user.last_sign_in_at)}", style: 'font-weight: bold' %>
    <% end %>
  </ul>
</div>